export const ICON_NAMES = {
  'carret-left': 'carret-left',
  attachment: 'attachment',
  user: 'user',
  telegram: 'telegram',
  star: 'star',
  settings: 'settings',
  search: 'search',
  projects: 'projects',
  plus: 'plus',
  phone: 'phone',
  members: 'members',
  mail: 'mail',
  cross: 'cross',
  filter: 'filter',
  'carret-right': 'carret-right',
  bell: 'bell',
  up: 'up',
  down: 'down',
  bookmark: 'bookmark',
} as const;
