export const STRINGS = {
  create: 'Создай',
  yourAccount: 'Свой Аккаунт',
  username: 'Имя Пользователя',
  email: 'Почта',
  password: 'Пароль',
  signUp: 'Регистрация',
  alreadyHave: 'Уже есть аккаунт?',
  login: 'Войти',
  logInto: 'Войдите в',
  account: 'Аккаунт',
  dontHave: 'Еще нет аккаунта?',
  members: 'Участники',
  seeAll: 'Посмотреть Всех',
  add: 'Добавить',
  archive: 'В Архиве',
  inProgress: 'В Работе',
  inReview: 'Проверка',
  done: 'Сделано',
  weight: 'Сложность',
  deadline: 'Крайний Срок',
  daysShort: 'Д',
  settings: 'Настройки',
  phone: 'Телефон',
  mail: 'Почта',
  telegram: 'Телеграм',
  exit: 'Выход',
  h: 'Ч',
  day: 'Дн',
  notes: 'Заметки',
  write: 'Печатать',
  projectMembers: 'Участники Проекта',
  performance: 'Загруженность',
  member: 'Участник',
  tasks: 'Задачи',
  team: 'Команда',
  projects: 'Проекты',
  newProjectNameGeneric: 'Новый Проект',
  newProjectDescriptionGeneric: 'Описание Нового Проекта',
  newTaskNameGeneric: 'Новая Задача',
  newTaskDescriptionGeneric: 'Описание Новой Задачи',
  rolePlaceholder: 'роль',
  placeHolderUsername: 'Введите Имя Пользователя',
  addMember: 'Добавить Участника',
};
