export const STRINGS = {
  create: 'Создай',
  yourAccount: 'Свой Аккаунт',
  username: 'Имя Пользователя',
  email: 'Почта',
  password: 'Пароль',
  signUp: 'Регистрация',
  alreadyHave: 'Уже есть аккаунт?',
  login: 'Войти',
  logInto: 'Войдите в',
  account: 'Аккаунт',
  dontHave: 'Еще нет аккаунта?',
  members: 'Участники',
  seeAll: 'Посмотреть Всех',
  add: 'Добавить',
  archive: 'В Архиве',
  inProgress: 'В Работе',
  inReview: 'Проверка',
  done: 'Сделано',
  weight: 'Сложность',
  deadline: 'Крайний Срок',
  daysShort: 'D',
  settings: 'Settings',
  phone: 'Phone',
  mail: 'Mail',
  telegram: 'Telegram',
  exit: 'Exit',
  h: 'H',
  day: 'Day',
  notes: 'Notes',
  write: 'Write',
  projectMembers: 'Project Members',
  performance: 'Performance',
  member: 'Member',
  tasks: 'Tasks',
  team: 'Team',
  projects: 'Projects',
};
